/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_App */

#ifndef _Included_org_example_App
#define _Included_org_example_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_App
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_App_foo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
